import { Bot, ExternalLink, LibraryBig, Pause, Rocket, Search, WandSparkles } from "lucide-react";
import { useMemo, useState } from "react";
import { Link, useNavigate } from "react-router";
import { Badge, StatusPill } from "../../components/Badge.tsx";
import { Button, ButtonLink } from "../../components/Button.tsx";
import { Card, PageHeader } from "../../components/Card.tsx";
import { EmptyState } from "../../components/EmptyState.tsx";
import { Page } from "../../components/Layout.tsx";
import { ErrorState, Skeleton } from "../../components/Spinner.tsx";
import { Segmented } from "../../components/Tabs.tsx";
import { timeAgo } from "../../lib/format.ts";
import { archetypeIcon } from "../../lib/icons.tsx";
import { ARCHETYPE_LABELS, archetypeLabel } from "../../lib/labels.ts";
import { useAgents, useDepartmentName } from "../../lib/queries.ts";
import type { AgentRow } from "../../types.ts";
import { useAgentMutations } from "./agentActions.ts";

const SOURCE_LABELS: Record<string, string> = { template: "Template", builder: "Agent Builder", manual: "Manual" };

type StatusFilter = "all" | "active" | "testing" | "draft" | "paused";

export default function AgentsList() {
  const { data, isLoading, error, refetch } = useAgents();
  const { setStatus } = useAgentMutations();
  const departmentName = useDepartmentName();
  const navigate = useNavigate();
  const [query, setQuery] = useState("");
  const [status, setStatusFilter] = useState<StatusFilter>("all");
  const [department, setDepartment] = useState("");
  const [archetype, setArchetype] = useState("");
  const [source, setSource] = useState("");

  const departments = useMemo(() => [...new Set((data ?? []).map((a) => a.department).filter((d): d is string => Boolean(d)))].sort(), [data]);

  const filtered = useMemo(() => {
    const q = query.trim().toLowerCase();
    return (data ?? []).filter(
      (a) =>
        (status === "all" || a.status === status) &&
        (!department || a.department === department) &&
        (!archetype || a.archetype === archetype) &&
        (!source || a.source === source) &&
        (!q || `${a.name} ${a.summary} ${a.slug} ${a.title ?? ""}`.toLowerCase().includes(q)),
    );
  }, [data, query, status, department, archetype, source]);

  const counts = useMemo(() => {
    const c: Record<string, number> = {};
    for (const a of data ?? []) c[a.status] = (c[a.status] ?? 0) + 1;
    return c;
  }, [data]);

  const toggle = (a: AgentRow) => setStatus.mutate({ slug: a.slug, status: a.status === "active" ? "paused" : "active" });

  return (
    <Page>
      <PageHeader
        icon={Bot}
        title="Agents"
        description="Every agent installed from the catalog, generated by the Agent Builder or created by hand — with its status, version and screen."
        actions={
          <>
            <ButtonLink to="/catalog?tab=agents" icon={LibraryBig}>
              Install from catalog
            </ButtonLink>
            <ButtonLink to="/builder/new" variant="primary" icon={WandSparkles}>
              Build an agent
            </ButtonLink>
          </>
        }
      />
      {error && <ErrorState error={error} onRetry={() => void refetch()} />}
      <Card className="overflow-hidden">
        <div className="flex flex-col gap-3 border-b border-line p-4 lg:flex-row lg:items-center">
          <div className="relative min-w-0 flex-1 lg:max-w-xs">
            <Search className="pointer-events-none absolute top-1/2 left-3 size-4 -translate-y-1/2 text-faint" />
            <input className="input pl-9" placeholder="Search agents" value={query} onChange={(e) => setQuery(e.target.value)} aria-label="Search agents" />
          </div>
          <Segmented
            value={status}
            onChange={setStatusFilter}
            options={[
              { value: "all", label: `All${data ? ` ${data.length}` : ""}` },
              { value: "active", label: `Active ${counts.active ?? 0}` },
              { value: "testing", label: `Testing ${counts.testing ?? 0}` },
              { value: "draft", label: `Draft ${counts.draft ?? 0}` },
              { value: "paused", label: `Paused ${counts.paused ?? 0}` },
            ]}
            className="overflow-x-auto"
          />
          <div className="flex flex-wrap gap-2 lg:ml-auto">
            <select className="input h-9 w-auto py-1.5" value={department} onChange={(e) => setDepartment(e.target.value)} aria-label="Department">
              <option value="">All departments</option>
              {departments.map((d) => (
                <option key={d} value={d}>
                  {departmentName(d)}
                </option>
              ))}
            </select>
            <select className="input h-9 w-auto py-1.5" value={archetype} onChange={(e) => setArchetype(e.target.value)} aria-label="Type">
              <option value="">All types</option>
              {Object.entries(ARCHETYPE_LABELS).map(([k, v]) => (
                <option key={k} value={k}>
                  {v}
                </option>
              ))}
            </select>
            <select className="input h-9 w-auto py-1.5" value={source} onChange={(e) => setSource(e.target.value)} aria-label="Source">
              <option value="">All sources</option>
              {Object.entries(SOURCE_LABELS).map(([k, v]) => (
                <option key={k} value={k}>
                  {v}
                </option>
              ))}
            </select>
          </div>
        </div>
        {isLoading && (
          <div className="space-y-2 p-4">
            {[0, 1, 2, 3].map((i) => (
              <Skeleton key={i} className="h-12" />
            ))}
          </div>
        )}
        {data && data.length === 0 && (
          <EmptyState
            className="m-4"
            icon={Bot}
            title="No agents yet"
            description="Install a department from the catalog to get a team of ready-made agents, or describe a new one to the Agent Builder."
            action={
              <>
                <ButtonLink to="/catalog" icon={LibraryBig}>
                  Browse the catalog
                </ButtonLink>
                <ButtonLink to="/builder/new" variant="primary" icon={WandSparkles}>
                  Build an agent
                </ButtonLink>
              </>
            }
          />
        )}
        {data && data.length > 0 && filtered.length === 0 && <p className="px-5 py-10 text-center text-sm text-muted">No agents match these filters.</p>}
        {filtered.length > 0 && (
          <div className="overflow-x-auto">
            <table className="w-full text-left text-sm">
              <thead className="border-b border-line bg-subtle/50 text-xs text-muted">
                <tr>
                  <th className="px-4 py-2.5 font-medium">Agent</th>
                  <th className="px-4 py-2.5 font-medium">Department</th>
                  <th className="px-4 py-2.5 font-medium">Type</th>
                  <th className="px-4 py-2.5 font-medium">Status</th>
                  <th className="px-4 py-2.5 font-medium">Source</th>
                  <th className="px-4 py-2.5 font-medium">Version</th>
                  <th className="px-4 py-2.5 font-medium">Updated</th>
                  <th className="px-4 py-2.5 text-right font-medium">
                    <span className="sr-only">Actions</span>
                  </th>
                </tr>
              </thead>
              <tbody className="divide-y divide-line">
                {filtered.map((a) => {
                  const Icon = archetypeIcon(a.archetype);
                  const busy = setStatus.isPending && setStatus.variables?.slug === a.slug;
                  return (
                    <tr key={a.id} className="cursor-pointer align-middle hover:bg-subtle/50" onClick={() => navigate(`/agents/${a.slug}`)}>
                      <td className="max-w-[22rem] px-4 py-3">
                        <div className="flex items-center gap-3">
                          <span className="flex size-8 shrink-0 items-center justify-center rounded-lg bg-brand-50 text-brand-600 dark:bg-brand-400/15 dark:text-brand-300">
                            <Icon className="size-4" />
                          </span>
                          <div className="min-w-0">
                            <Link to={`/agents/${a.slug}`} onClick={(e) => e.stopPropagation()} className="block truncate font-medium text-fg hover:underline">
                              {a.name}
                            </Link>
                            <p className="truncate text-xs text-muted">{a.summary}</p>
                          </div>
                        </div>
                      </td>
                      <td className="px-4 py-3 whitespace-nowrap text-muted">{departmentName(a.department)}</td>
                      <td className="px-4 py-3 whitespace-nowrap text-muted">{archetypeLabel(a.archetype)}</td>
                      <td className="px-4 py-3">
                        <StatusPill status={a.status} size="xs" />
                      </td>
                      <td className="px-4 py-3">
                        <Badge size="xs" tone={a.source === "builder" ? "brand" : "neutral"}>
                          {SOURCE_LABELS[a.source] ?? a.source}
                        </Badge>
                      </td>
                      <td className="px-4 py-3 text-muted tabular-nums">v{a.version}</td>
                      <td className="px-4 py-3 whitespace-nowrap text-muted">{timeAgo(a.updatedAt)}</td>
                      <td className="px-4 py-3" onClick={(e) => e.stopPropagation()}>
                        <div className="flex justify-end gap-1.5">
                          {a.status !== "archived" && (
                            <Button
                              size="xs"
                              variant={a.status === "active" ? "ghost" : "soft"}
                              icon={a.status === "active" ? Pause : Rocket}
                              loading={busy}
                              onClick={() => toggle(a)}
                            >
                              {a.status === "active" ? "Pause" : "Activate"}
                            </Button>
                          )}
                          {a.ui?.layout !== "none" && (
                            <ButtonLink size="xs" variant="ghost" to={`/apps/${a.slug}`} icon={ExternalLink}>
                              App
                            </ButtonLink>
                          )}
                        </div>
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        )}
      </Card>
    </Page>
  );
}
